### ISSUE TITLE
After the instruction in README, yarn install, run client and server dev,  meet an error, seems fail to create user data 

### ISSUE THREAD

**Issue by lizhiyu-me** [oriongunning/t5c#22]
caught (in promise) TypeError: Cannot set properties of undefined (setting 'location')
    at CharacterEditor.<anonymous> (CharacterEditor.ts:87:1)
    at Generator.next (<anonymous>)
    at fulfilled (CharacterEditor.ts:5:43)

**Comment by orion3dgames** [comment]
this should not be happening anymore

**Comment by lizhiyu-me** [comment]
> this should not be happening anymore

thanks a lot
