### ISSUE TITLE
npm dev : Unknown command: "dev"

### ISSUE THREAD

**Issue by ddaydd** [oriongunning/t5c#5]
Did you mean this?

npm run dev

SyntaxError: Unexpected token '.'

 path__default['default'].resolve(path__default['default'].dirname(require?.main?.filename || process.cwd()), "..", envFilename),

**Comment by orion3dgames** [comment]
well i use yarn, i never tried with npm, if you're not sure, just check what command is available in the package.json under the scripts variable.

**Comment by ddaydd** [comment]
by updating node, "npm run dev" works
